version: "3.9"
services:
  app:
    depends_on:
      - "db"
    entrypoint: /bin/bash
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/queryhw
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5438:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # copy the scripts to initialize the db
      - ./data/cpu_usage.csv:/docker-entrypoint-initdb.d/cpu_usage.csv
      - ./data/cpu_usage.sql:/docker-entrypoint-initdb.d/000-cpu_usage.sql
      - ./data/initdb.sh:/docker-entrypoint-initdb.d/001-initdb.sh